dist: xenial
sudo: false
cache: pip
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
matrix:
  include:
    - os: osx
      language: generic
      python: 2.7
    - os: osx
      language: sh
      python: 3.7
      before_install:
        - brew update
        - brew upgrade python
        - python3 -m venv venv
        - source venv/bin/activate
    - os: windows
      language: sh
      python: 2.7
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: 3.7
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
  allow_failures:
    - os: linux
      python: 3.8-dev
    - os: windows
addons:
  apt:
    packages:
      - gdb
      - valgrind
before_install:
  - pip install --upgrade setuptools pip
install:
  - python -m pip install -e .
before_script:
  - pip install --upgrade pytest pytest-pylint pytest-cov codecov
script:
  - python -m pytest
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mozillasecurity
  password:
    secure: jCG9YTWqSMMsbDEuIgLov4ke4r/zEzZSugi+Nkw28WCplaM0Q9PXuwfYpajXECBp3osZd7LAiLAVA8eNUELotFJz2dRLBQPbKa7rqVfKsFSMkZ1bHC5pfckJ2pAKDFx4ty5sB0MnxZKeYMWiXF8GvySne8n/j9LLv6ihF0nM/u7VOG9jFIYGd5uG4RFISbVA4eHZ7jkdKqBPO85+TrgOW4CldsVyRntw0Iuixt5oW+gE9TU8WS1HhvDblDk5+Qu4AgUYPfs2N0C6aox615OuK6BTWaX6VdJcAJpNchkgrtaHgwNXoBze1q63SOW9AiqnbgROwThQ6le24v34oBZ1MK/6NE7723HkYWfqsvVQlugvO6KCMKy6LChLV21jqFuiO023jzLajnvq91Qz/STY/plXPgf7AYRCOjUgarqXqpt4Fhue+lsUmRUus66YgYMRFqYfQVuW2n/BZtuCUGKsOOB2YHB6+17FzRcABF48+60MCDrR1tgAO5VwQH1e7EDxcuaM0Wd3fIcWa0EVe2k1IXlCneJTVOS610ZaRCOdKCoZG5LgO6oobY4l64vCW8sjVVPDYsfjWrtY5DXeGlwD3qhz0ddRD62usfGgGMPUTlDvL6kpJhhuItZ+cjJ0f4/b+cX9tH7WbB1uBvF+PYS4xoLR/cQW31OOxMk1LoV17ns=
  on:
    tags: true
