language: python
sudo: true

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7-dev
    - os: osx
      language: generic
  allow_failures:
    - os: linux
      python: 3.8-dev

addons:
  apt:
    packages:
      - gdb
      - valgrind

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then LATEST_VERSION="$(curl -Ls 'https://api.github.com/repos/mozilla/rr/releases/latest' | python -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['tag_name'])")"; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo sysctl kernel.perf_event_paranoid=1; curl -L -o /tmp/rr.deb "https://github.com/mozilla/rr/releases/download/$LATEST_VERSION/rr-$LATEST_VERSION-Linux-$(uname -m).deb"; sudo dpkg -i /tmp/rr.deb; rm /tmp/rr.deb; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip2 install pytest; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip2 install -r requirements.txt; else pip install -r requirements.txt; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]] && [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then pip install pylint pytest-cov python-coveralls; fi

script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]] && [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then pytest -v --cov=. --cov-report term-missing --cov-config .coveragerc && pylint --errors-only --ignored-classes=_socketobject --ignore=testff.py,testmdsw.py,debugger_windbg.py ffpuppet; else pytest -v; fi

after_success:
  - if [[ $TRAVIS_OS_NAME == "linux" ]] && [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then coveralls; fi
