dist: xenial
sudo: false
cache: pip
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
matrix:
  include:
    - os: osx
      language: generic
      python: 2.7
    - os: windows
      language: sh
      python: 2.7
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: 3.7
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
  allow_failures:
    - os: linux
      python: 3.8-dev
addons:
  apt:
    packages:
      - gdb
      - valgrind
before_install:
  - pip install --upgrade setuptools pip
install:
  - python -m pip install -e .
before_script:
  - pip install --upgrade pytest python-coveralls pylint
  - pip install --upgrade pytest-pylint pytest-cov
script:
  - python -m pytest
after_success:
  - coveralls
