dist: bionic
cache: pip
language: python
os: linux
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      language: shell
    - os: windows
      python: 3.8
      language: shell
      before_install:
        - choco install python --version 3.8
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
addons:
  apt:
    packages:
      - gdb
      - valgrind
before_install:
  - pip3 install --upgrade setuptools pip
install:
  - pip3 install -e .
before_script:
  - pip3 install --upgrade pytest pytest-mock pytest-pylint pytest-cov codecov
script:
  - pytest
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: mozillasecurity
  password:
    secure: jCG9YTWqSMMsbDEuIgLov4ke4r/zEzZSugi+Nkw28WCplaM0Q9PXuwfYpajXECBp3osZd7LAiLAVA8eNUELotFJz2dRLBQPbKa7rqVfKsFSMkZ1bHC5pfckJ2pAKDFx4ty5sB0MnxZKeYMWiXF8GvySne8n/j9LLv6ihF0nM/u7VOG9jFIYGd5uG4RFISbVA4eHZ7jkdKqBPO85+TrgOW4CldsVyRntw0Iuixt5oW+gE9TU8WS1HhvDblDk5+Qu4AgUYPfs2N0C6aox615OuK6BTWaX6VdJcAJpNchkgrtaHgwNXoBze1q63SOW9AiqnbgROwThQ6le24v34oBZ1MK/6NE7723HkYWfqsvVQlugvO6KCMKy6LChLV21jqFuiO023jzLajnvq91Qz/STY/plXPgf7AYRCOjUgarqXqpt4Fhue+lsUmRUus66YgYMRFqYfQVuW2n/BZtuCUGKsOOB2YHB6+17FzRcABF48+60MCDrR1tgAO5VwQH1e7EDxcuaM0Wd3fIcWa0EVe2k1IXlCneJTVOS610ZaRCOdKCoZG5LgO6oobY4l64vCW8sjVVPDYsfjWrtY5DXeGlwD3qhz0ddRD62usfGgGMPUTlDvL6kpJhhuItZ+cjJ0f4/b+cX9tH7WbB1uBvF+PYS4xoLR/cQW31OOxMk1LoV17ns=
  on:
    branch: master
    tags: true
    os: linux
    python: 3.8
