dist: xenial
sudo: false
cache: pip
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
matrix:
  include:
    - os: osx
      language: sh
      python: 2.7
      before_install:
        - brew update
        - brew upgrade python
        - python3 -m venv venv
        - source venv/bin/activate
    - os: osx
      language: sh
      python: 3.7
      before_install:
        - brew update
        - brew upgrade python
        - python -m venv venv
        - source venv/bin/activate
    - os: windows
      language: sh
      python: 3.7
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: 2.7
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
addons:
  apt:
    packages:
      - gdb
      - valgrind
before_install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade "psutil >= 4.4.0" "xvfbwrapper >= 0.2.9; sys_platform == 'linux' or sys_platform == 'linux2'"
  - pip install --upgrade pytest python-coveralls pylint
  - pip install --upgrade pytest-pylint pytest-cov
script:
  - python -m pytest
after_success:
  - coveralls
